name: Build and Deploy Python App to Azure Web App - ChabotTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read  # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r OutreachX/helpdesk-assistant/requirements.txt

      - name: Ensure requirements.txt is included
        run: cp OutreachX/helpdesk-assistant/requirements.txt ./  

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      # ✅ Azure Login using Federated Identity (OIDC)
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ✅ Log in to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # ✅ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ChabotTest \
            --resource-group testingrg \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/rasa:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io

      # ✅ Restart Web App after deployment
      - name: Restart Azure Web App
        run: |
          az webapp restart --name ChabotTest --resource-group testingrg
