name: Build and Deploy Python App to Azure Web App - ChabotTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies before deployment
        run: pip install -r OutreachX/helpdesk-assistant/requirements.txt

      - name: Ensure requirements.txt is included in the deployment package
        run: cp OutreachX/helpdesk-assistant/requirements.txt ./  # Copy it to the root directory

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # ✅ Deploy using the correct Azure Web App SCM URL
      - name: Deploy to Azure Web App using ZIP Deploy API
        run: |
          response=$(curl -w "%{http_code}" -X POST "https://chabottest-h8drbhaugxetbhcw.scm.canadacentral-01.azurewebsites.net/api/zipdeploy" \
               --data-binary @release.zip -o response.log)
          if [[ "$response" -ne 200 && "$response" -ne 202 ]]; then
            echo "Deployment failed. Check response.log for details."
            cat response.log
            exit 1
          fi

      # ✅ Check if the directory exists before running ls
      - name: Verify files in Azure Web App
        run: |
          if [ -d "/home/site/wwwroot/" ]; then
            ls -la /home/site/wwwroot/
          else
            echo "Directory /home/site/wwwroot/ does not exist. Deployment might have failed."
            exit 1
          fi

      # ✅ Install dependencies in Azure Web App
      - name: Install dependencies in Azure Web App
        run: |
          if [ -d "/home/site/wwwroot/" ]; then
            cd /home/site/wwwroot/
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          else
            echo "Cannot install dependencies: /home/site/wwwroot/ does not exist."
            exit 1
          fi
