name: Build and Deploy Rasa App to Azure Web App - ChabotTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read  # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r OutreachX/helpdesk-assistant/requirements.txt

      - name: Build Docker image
        working-directory: ./OutreachX/helpdesk-assistant
        run: |
          docker build -f Dockerfile.chatroom -t ${{ secrets.ACR_NAME }}.azurecr.io/your-image:latest .

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/your-image:latest

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: rasa-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: rasa-app

      - name: Unzip artifact
        run: unzip release.zip

      # ✅ Azure Login using Federated Identity (OIDC)
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ✅ Deploy to Azure Web App
      - name: Deploy helpdesk-assistant to Azure App Service
        run: |
          az webapp config container set \
            --name ChabotTest \
            --resource-group testingrg \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/your-image:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io

      # ✅ Copy helpdesk-assistant folder to wwwroot
      - name: Copy files to Azure App Service
        run: |
          az webapp create-remote-connection --name ChabotTest --resource-group testingrg
          rsync -avz ./helpdesk-assistant/ /home/site/wwwroot/helpdesk-assistant/

      # ✅ Create Virtual Environment on App Service
      - name: Setup virtual environment on App Service
        run: |
          cd /home/site/wwwroot/helpdesk-assistant
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Start Duckling for NLP
      - name: Start Duckling Server
        run: |
          docker run -p 8000:8000 rasa/duckling &

      # ✅ Run Rasa API and Actions Server
      - name: Start Rasa Services
        run: |
          cd /home/site/wwwroot/helpdesk-assistant
          source venv/bin/activate
          rasa run --enable-api --cors "*" &
          rasa run actions --cors "*" &

      # ✅ Restart Web App after deployment
      - name: Restart Azure Web App
        run: |
          az webapp restart --name ChabotTest --resource-group testingrg
